### ISSUE TITLE
Oasis Issue [Medium] - DefiLlama Adapter

### ISSUE THREAD

**Issue by ControlCplusControlV** [CogFinance/Cog-Isolated-Lending#66]
**Difficulty** - Medium

Please write a [Defi-Llama adapter for Cog ](https://github.com/DefiLlama/DefiLlama-Adapters), the best strategy would be to filter the events of the [Cog Factory](https://github.com/CogFinance/Cog-Isolated-Lending/blob/main/src/cog_factory.vy) for all 4 types of pairs, then iterate through each pair checking `totalAssets` and the `collateral` token balance, and the sum of that should equal the TvL.

Please add issues you encounter or run into, a successful PR would be one which is made to [adapters](https://github.com/DefiLlama/DefiLlama-Adapters) and accepted by the llamas

**Comment by herpq** [comment]
closing because we have a PR open already
