### ISSUE TITLE
Oasis Issue [High] - Bunni Oracle

### ISSUE THREAD

**Issue by ControlCplusControlV** [CogFinance/Cog-Isolated-Lending#68]
**Difficulty** - High

Please provide a Vyper oracle which fetches a price feed for a Uniswap-V3 Position using [Bunni](https://github.com/ZeframLou/bunni/blob/main/src/BunniLens.sol) to price Bunni tokens, which are ERC20 versions of Uniswap-V3 Positions. Then write either foundry fork tests, or titanoboa python tests to confirm the test works, use common pairs like WETH-USDC, and USDC-DAI to confirm your work.

Can provide guidance as you ask

**Comment by ericmartihaynes** [comment]
Going to have a look at this, will let you know if I have any questions

**Comment by ControlCplusControlV** [comment]
Sounds great, hmu if you have any questions

**Comment by ericmartihaynes** [comment]
@ControlCplusControlV I think this can be closed now
